//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdtime.Members {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiCredentials", Namespace="http://connectwise.com")]
    [System.SerializableAttribute()]
    public partial class ApiCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIdField;
        
        private System.Nullable<int> ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntegratorLoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntegratorPasswordField;
        
        private System.Nullable<int> PortalConfigIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIdField, value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((this.ContactIdField.Equals(value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IntegratorLoginId {
            get {
                return this.IntegratorLoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegratorLoginIdField, value) != true)) {
                    this.IntegratorLoginIdField = value;
                    this.RaisePropertyChanged("IntegratorLoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IntegratorPassword {
            get {
                return this.IntegratorPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegratorPasswordField, value) != true)) {
                    this.IntegratorPasswordField = value;
                    this.RaisePropertyChanged("IntegratorPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PortalConfigId {
            get {
                return this.PortalConfigIdField;
            }
            set {
                if ((this.PortalConfigIdField.Equals(value) != true)) {
                    this.PortalConfigIdField = value;
                    this.RaisePropertyChanged("PortalConfigId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MachineId {
            get {
                return this.MachineIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineIdField, value) != true)) {
                    this.MachineIdField = value;
                    this.RaisePropertyChanged("MachineId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSupportPackage", Namespace="http://connectwise.com")]
    public enum RemoteSupportPackage : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogMeIn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NtrSupport = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberFindResult", Namespace="http://connectwise.com")]
    [System.SerializableAttribute()]
    public partial class MemberFindResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connectwise.com", ConfigurationName="Members.MemberApiSoap")]
    public interface MemberApiSoap {
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://connectwise.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://connectwise.com/IsValidMemberIdAndPassword", ReplyAction="*")]
        sdtime.Members.IsValidMemberIdAndPasswordResponse IsValidMemberIdAndPassword(sdtime.Members.IsValidMemberIdAndPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://connectwise.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://connectwise.com/CreateAuthenticatedMemberHashToken", ReplyAction="*")]
        sdtime.Members.CreateAuthenticatedMemberHashTokenResponse CreateAuthenticatedMemberHashToken(sdtime.Members.CreateAuthenticatedMemberHashTokenRequest request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://connectwise.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://connectwise.com/GetMemberIdByRemoteSupportPackageAuthenticationCredentials" +
            "", ReplyAction="*")]
        sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse GetMemberIdByRemoteSupportPackageAuthenticationCredentials(sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://connectwise.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://connectwise.com/FindMembers", ReplyAction="*")]
        sdtime.Members.FindMembersResponse FindMembers(sdtime.Members.FindMembersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidMemberIdAndPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidMemberIdAndPassword", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.IsValidMemberIdAndPasswordRequestBody Body;
        
        public IsValidMemberIdAndPasswordRequest() {
        }
        
        public IsValidMemberIdAndPasswordRequest(sdtime.Members.IsValidMemberIdAndPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class IsValidMemberIdAndPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sdtime.Members.ApiCredentials credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string memberId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public IsValidMemberIdAndPasswordRequestBody() {
        }
        
        public IsValidMemberIdAndPasswordRequestBody(sdtime.Members.ApiCredentials credentials, string memberId, string password) {
            this.credentials = credentials;
            this.memberId = memberId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidMemberIdAndPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidMemberIdAndPasswordResponse", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.IsValidMemberIdAndPasswordResponseBody Body;
        
        public IsValidMemberIdAndPasswordResponse() {
        }
        
        public IsValidMemberIdAndPasswordResponse(sdtime.Members.IsValidMemberIdAndPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class IsValidMemberIdAndPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsValidMemberIdAndPasswordResult;
        
        public IsValidMemberIdAndPasswordResponseBody() {
        }
        
        public IsValidMemberIdAndPasswordResponseBody(bool IsValidMemberIdAndPasswordResult) {
            this.IsValidMemberIdAndPasswordResult = IsValidMemberIdAndPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAuthenticatedMemberHashTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAuthenticatedMemberHashToken", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.CreateAuthenticatedMemberHashTokenRequestBody Body;
        
        public CreateAuthenticatedMemberHashTokenRequest() {
        }
        
        public CreateAuthenticatedMemberHashTokenRequest(sdtime.Members.CreateAuthenticatedMemberHashTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class CreateAuthenticatedMemberHashTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sdtime.Members.ApiCredentials credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string memberId;
        
        public CreateAuthenticatedMemberHashTokenRequestBody() {
        }
        
        public CreateAuthenticatedMemberHashTokenRequestBody(sdtime.Members.ApiCredentials credentials, string companyId, string memberId) {
            this.credentials = credentials;
            this.companyId = companyId;
            this.memberId = memberId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAuthenticatedMemberHashTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAuthenticatedMemberHashTokenResponse", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.CreateAuthenticatedMemberHashTokenResponseBody Body;
        
        public CreateAuthenticatedMemberHashTokenResponse() {
        }
        
        public CreateAuthenticatedMemberHashTokenResponse(sdtime.Members.CreateAuthenticatedMemberHashTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class CreateAuthenticatedMemberHashTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateAuthenticatedMemberHashTokenResult;
        
        public CreateAuthenticatedMemberHashTokenResponseBody() {
        }
        
        public CreateAuthenticatedMemberHashTokenResponseBody(string CreateAuthenticatedMemberHashTokenResult) {
            this.CreateAuthenticatedMemberHashTokenResult = CreateAuthenticatedMemberHashTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberIdByRemoteSupportPackageAuthenticationCredentials", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody Body;
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest() {
        }
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest(sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sdtime.Members.ApiCredentials credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public sdtime.Members.RemoteSupportPackage remoteSupportPackage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody() {
        }
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody(sdtime.Members.ApiCredentials credentials, sdtime.Members.RemoteSupportPackage remoteSupportPackage, string username, string password) {
            this.credentials = credentials;
            this.remoteSupportPackage = remoteSupportPackage;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponseBody Body;
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse() {
        }
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse(sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResult;
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponseBody() {
        }
        
        public GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponseBody(string GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResult) {
            this.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResult = GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMembers", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.FindMembersRequestBody Body;
        
        public FindMembersRequest() {
        }
        
        public FindMembersRequest(sdtime.Members.FindMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class FindMembersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sdtime.Members.ApiCredentials credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string conditions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> limit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> skip;
        
        public FindMembersRequestBody() {
        }
        
        public FindMembersRequestBody(sdtime.Members.ApiCredentials credentials, string conditions, string orderBy, System.Nullable<int> limit, System.Nullable<int> skip) {
            this.credentials = credentials;
            this.conditions = conditions;
            this.orderBy = orderBy;
            this.limit = limit;
            this.skip = skip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMembersResponse", Namespace="http://connectwise.com", Order=0)]
        public sdtime.Members.FindMembersResponseBody Body;
        
        public FindMembersResponse() {
        }
        
        public FindMembersResponse(sdtime.Members.FindMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://connectwise.com")]
    public partial class FindMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sdtime.Members.MemberFindResult[] FindMembersResult;
        
        public FindMembersResponseBody() {
        }
        
        public FindMembersResponseBody(sdtime.Members.MemberFindResult[] FindMembersResult) {
            this.FindMembersResult = FindMembersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberApiSoapChannel : sdtime.Members.MemberApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberApiSoapClient : System.ServiceModel.ClientBase<sdtime.Members.MemberApiSoap>, sdtime.Members.MemberApiSoap {
        
        public MemberApiSoapClient() {
        }
        
        public MemberApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdtime.Members.IsValidMemberIdAndPasswordResponse sdtime.Members.MemberApiSoap.IsValidMemberIdAndPassword(sdtime.Members.IsValidMemberIdAndPasswordRequest request) {
            return base.Channel.IsValidMemberIdAndPassword(request);
        }
        
        public bool IsValidMemberIdAndPassword(sdtime.Members.ApiCredentials credentials, string memberId, string password) {
            sdtime.Members.IsValidMemberIdAndPasswordRequest inValue = new sdtime.Members.IsValidMemberIdAndPasswordRequest();
            inValue.Body = new sdtime.Members.IsValidMemberIdAndPasswordRequestBody();
            inValue.Body.credentials = credentials;
            inValue.Body.memberId = memberId;
            inValue.Body.password = password;
            sdtime.Members.IsValidMemberIdAndPasswordResponse retVal = ((sdtime.Members.MemberApiSoap)(this)).IsValidMemberIdAndPassword(inValue);
            return retVal.Body.IsValidMemberIdAndPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdtime.Members.CreateAuthenticatedMemberHashTokenResponse sdtime.Members.MemberApiSoap.CreateAuthenticatedMemberHashToken(sdtime.Members.CreateAuthenticatedMemberHashTokenRequest request) {
            return base.Channel.CreateAuthenticatedMemberHashToken(request);
        }
        
        public string CreateAuthenticatedMemberHashToken(sdtime.Members.ApiCredentials credentials, string companyId, string memberId) {
            sdtime.Members.CreateAuthenticatedMemberHashTokenRequest inValue = new sdtime.Members.CreateAuthenticatedMemberHashTokenRequest();
            inValue.Body = new sdtime.Members.CreateAuthenticatedMemberHashTokenRequestBody();
            inValue.Body.credentials = credentials;
            inValue.Body.companyId = companyId;
            inValue.Body.memberId = memberId;
            sdtime.Members.CreateAuthenticatedMemberHashTokenResponse retVal = ((sdtime.Members.MemberApiSoap)(this)).CreateAuthenticatedMemberHashToken(inValue);
            return retVal.Body.CreateAuthenticatedMemberHashTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse sdtime.Members.MemberApiSoap.GetMemberIdByRemoteSupportPackageAuthenticationCredentials(sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest request) {
            return base.Channel.GetMemberIdByRemoteSupportPackageAuthenticationCredentials(request);
        }
        
        public string GetMemberIdByRemoteSupportPackageAuthenticationCredentials(sdtime.Members.ApiCredentials credentials, sdtime.Members.RemoteSupportPackage remoteSupportPackage, string username, string password) {
            sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest inValue = new sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequest();
            inValue.Body = new sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsRequestBody();
            inValue.Body.credentials = credentials;
            inValue.Body.remoteSupportPackage = remoteSupportPackage;
            inValue.Body.username = username;
            inValue.Body.password = password;
            sdtime.Members.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResponse retVal = ((sdtime.Members.MemberApiSoap)(this)).GetMemberIdByRemoteSupportPackageAuthenticationCredentials(inValue);
            return retVal.Body.GetMemberIdByRemoteSupportPackageAuthenticationCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdtime.Members.FindMembersResponse sdtime.Members.MemberApiSoap.FindMembers(sdtime.Members.FindMembersRequest request) {
            return base.Channel.FindMembers(request);
        }
        
        public sdtime.Members.MemberFindResult[] FindMembers(sdtime.Members.ApiCredentials credentials, string conditions, string orderBy, System.Nullable<int> limit, System.Nullable<int> skip) {
            sdtime.Members.FindMembersRequest inValue = new sdtime.Members.FindMembersRequest();
            inValue.Body = new sdtime.Members.FindMembersRequestBody();
            inValue.Body.credentials = credentials;
            inValue.Body.conditions = conditions;
            inValue.Body.orderBy = orderBy;
            inValue.Body.limit = limit;
            inValue.Body.skip = skip;
            sdtime.Members.FindMembersResponse retVal = ((sdtime.Members.MemberApiSoap)(this)).FindMembers(inValue);
            return retVal.Body.FindMembersResult;
        }
    }
}
