//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SupportModel", "FK_UserUserEmailConfirmation", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(sdtime.Util.Security.Model.User), "UserEmailConfirmations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(sdtime.Util.Security.Model.UserEmailConfirmation), true)]

#endregion

namespace sdtime.Util.Security.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContainerDb : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContainerDb object using the connection string found in the 'ContainerDb' section of the application configuration file.
        /// </summary>
        public ContainerDb() : base("name=ContainerDb", "ContainerDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContainerDb object.
        /// </summary>
        public ContainerDb(string connectionString) : base(connectionString, "ContainerDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContainerDb object.
        /// </summary>
        public ContainerDb(EntityConnection connection) : base(connection, "ContainerDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserEmailConfirmation> UserEmailConfirmations
        {
            get
            {
                if ((_UserEmailConfirmations == null))
                {
                    _UserEmailConfirmations = base.CreateObjectSet<UserEmailConfirmation>("UserEmailConfirmations");
                }
                return _UserEmailConfirmations;
            }
        }
        private ObjectSet<UserEmailConfirmation> _UserEmailConfirmations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserEmailConfirmations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserEmailConfirmations(UserEmailConfirmation userEmailConfirmation)
        {
            base.AddObject("UserEmailConfirmations", userEmailConfirmation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupportModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="displayName">Initial value of the DisplayName property.</param>
        /// <param name="identityProviderKey">Initial value of the IdentityProviderKey property.</param>
        /// <param name="identityProviderName">Initial value of the IdentityProviderName property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String displayName, global::System.String identityProviderKey, global::System.String identityProviderName)
        {
            User user = new User();
            user.Id = id;
            user.DisplayName = displayName;
            user.IdentityProviderKey = identityProviderKey;
            user.IdentityProviderName = identityProviderName;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MemberSince
        {
            get
            {
                return _MemberSince;
            }
            set
            {
                OnMemberSinceChanging(value);
                ReportPropertyChanging("MemberSince");
                _MemberSince = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberSince");
                OnMemberSinceChanged();
            }
        }
        private Nullable<global::System.DateTime> _MemberSince;
        partial void OnMemberSinceChanging(Nullable<global::System.DateTime> value);
        partial void OnMemberSinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdentityProviderKey
        {
            get
            {
                return _IdentityProviderKey;
            }
            set
            {
                OnIdentityProviderKeyChanging(value);
                ReportPropertyChanging("IdentityProviderKey");
                _IdentityProviderKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdentityProviderKey");
                OnIdentityProviderKeyChanged();
            }
        }
        private global::System.String _IdentityProviderKey;
        partial void OnIdentityProviderKeyChanging(global::System.String value);
        partial void OnIdentityProviderKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdentityProviderName
        {
            get
            {
                return _IdentityProviderName;
            }
            set
            {
                OnIdentityProviderNameChanging(value);
                ReportPropertyChanging("IdentityProviderName");
                _IdentityProviderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdentityProviderName");
                OnIdentityProviderNameChanged();
            }
        }
        private global::System.String _IdentityProviderName;
        partial void OnIdentityProviderNameChanging(global::System.String value);
        partial void OnIdentityProviderNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupportModel", "FK_UserUserEmailConfirmation", "UserEmailConfirmations")]
        public EntityCollection<UserEmailConfirmation> UserEmailConfirmations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserEmailConfirmation>("SupportModel.FK_UserUserEmailConfirmation", "UserEmailConfirmations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserEmailConfirmation>("SupportModel.FK_UserUserEmailConfirmation", "UserEmailConfirmations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupportModel", Name="UserEmailConfirmation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserEmailConfirmation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserEmailConfirmation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static UserEmailConfirmation CreateUserEmailConfirmation(global::System.Int32 id, global::System.Int32 userId)
        {
            UserEmailConfirmation userEmailConfirmation = new UserEmailConfirmation();
            userEmailConfirmation.Id = id;
            userEmailConfirmation.UserId = userId;
            return userEmailConfirmation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SentOn
        {
            get
            {
                return _SentOn;
            }
            set
            {
                OnSentOnChanging(value);
                ReportPropertyChanging("SentOn");
                _SentOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SentOn");
                OnSentOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _SentOn;
        partial void OnSentOnChanging(Nullable<global::System.DateTime> value);
        partial void OnSentOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ConfirmedOn
        {
            get
            {
                return _ConfirmedOn;
            }
            set
            {
                OnConfirmedOnChanging(value);
                ReportPropertyChanging("ConfirmedOn");
                _ConfirmedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConfirmedOn");
                OnConfirmedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ConfirmedOn;
        partial void OnConfirmedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnConfirmedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupportModel", "FK_UserUserEmailConfirmation", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SupportModel.FK_UserUserEmailConfirmation", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SupportModel.FK_UserUserEmailConfirmation", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SupportModel.FK_UserUserEmailConfirmation", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SupportModel.FK_UserUserEmailConfirmation", "Users", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
